export const country = [
  {
    name: "English",
    flag: "https://flagcdn.com/w320/us.png",
    code: "en",
    language: "English",
  },
  {
    name: "Switzerland",
    flag: "https://flagcdn.com/w320/ch.png",
    code: "de",
    language: "German",
  },
  {
    name: "Hungary",
    flag: "https://flagcdn.com/w320/hu.png",
    code: "hu",
    language: "Hungarian",
  },
  {
    name: "China",
    flag: "https://flagcdn.com/w320/cn.png",
    code: "zh",
    language: "Chinese",
  },
  {
    name: "France",
    flag: "https://flagcdn.com/w320/fr.png",
    code: "fr",
    language: "French",
  },
  {
    name: "Egypt",
    flag: "https://flagcdn.com/w320/eg.png",
    code: "ar",
    language: "Arabic",
  },
  {
    name: "Italy",
    flag: "https://flagcdn.com/w320/it.png",
    code: "it",
    language: "Italian",
  },
  {
    name: "Indonesia",
    flag: "https://flagcdn.com/w320/id.png",
    code: "id",
    language: "Indonesian",
  },
  {
    name: "Portugal",
    flag: "https://flagcdn.com/w320/pt.png",
    code: "pt",
    language: "Portuguese",
  },
  {
    name: "Laos",
    flag: "https://flagcdn.com/w320/la.png",
    code: "lo",
    language: "Lao",
  },
  {
    name: "Netherlands",
    flag: "https://flagcdn.com/w320/nl.png",
    code: "nl",
    language: "Dutch",
  },
  {
    name: "Andorra",
    flag: "https://flagcdn.com/w320/ad.png",
    code: "ca",
    language: "Catalan",
  },
  {
    name: "Spain",
    flag: "https://flagcdn.com/w320/es.png",
    code: "es",
    language: "Spanish",
  },
  {
    name: "North Macedonia",
    flag: "https://flagcdn.com/w320/mk.png",
    code: "mk",
    language: "Macedonian",
  },
  {
    name: "Norway",
    flag: "https://flagcdn.com/w320/no.png",
    code: "no",
    language: "Norwegian",
  },
  {
    name: "Faroe Islands",
    flag: "https://flagcdn.com/w320/fo.png",
    code: "fo",
    language: "Faroese",
  },
  {
    name: "Uzbekistan",
    flag: "https://flagcdn.com/w320/uz.png",
    code: "uz",
    language: "Uzbek",
  },
  {
    name: "Sri Lanka",
    flag: "https://flagcdn.com/w320/lk.png",
    code: "si",
    language: "Sinhala",
  },
  {
    name: "Bangladesh",
    flag: "https://flagcdn.com/w320/bd.png",
    code: "bn",
    language: "Bengali",
  },
  {
    name: "Turkey",
    flag: "https://flagcdn.com/w320/tr.png",
    code: "tr",
    language: "Turkish",
  },
  {
    name: "Afghanistan",
    flag: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
    code: "ps",
    language: "Pashto",
  },
  {
    name: "Finland",
    flag: "https://flagcdn.com/w320/fi.png",
    code: "fi",
    language: "Finnish",
  },
  {
    name: "Azerbaijan",
    flag: "https://flagcdn.com/w320/az.png",
    code: "az",
    language: "Azerbaijani",
  },
  {
    name: "South Korea",
    flag: "https://flagcdn.com/w320/kr.png",
    code: "ko",
    language: "Korean",
  },
  {
    name: "Greece",
    flag: "https://flagcdn.com/w320/gr.png",
    code: "el",
    language: "Greek",
  },
  {
    name: "Croatia",
    flag: "https://flagcdn.com/w320/hr.png",
    code: "hr",
    language: "Croatian",
  },
  {
    name: "Nepal",
    flag: "https://flagcdn.com/w320/np.png",
    code: "ne",
    language: "Nepali",
  },
  {
    name: "Georgia",
    flag: "https://flagcdn.com/w320/ge.png",
    code: "ka",
    language: "Georgian",
  },
  {
    name: "Pakistan",
    flag: "https://flagcdn.com/w320/pk.png",
    code: "ur",
    language: "Urdu",
  },
  {
    name: "India",
    flag: "https://flagcdn.com/w320/in.png",
    code: "hi",
    language: "Hindi",
  },
  {
    name: "Montenegro",
    flag: "https://flagcdn.com/w320/me.png",
    code: "sr",
    language: "Serbian",
  },
  {
    name: "Ukraine",
    flag: "https://flagcdn.com/w320/ua.png",
    code: "uk",
    language: "Ukrainian",
  },
  {
    name: "Bulgaria",
    flag: "https://flagcdn.com/w320/bg.png",
    code: "bg",
    language: "Bulgarian",
  },
  {
    name: "Greenland",
    flag: "https://flagcdn.com/w320/gl.png",
    code: "kl",
    language: "Kalaallisut",
  },
  {
    name: "Cambodia",
    flag: "https://flagcdn.com/w320/kh.png",
    code: "km",
    language: "Khmer",
  },
  {
    name: "Sweden",
    flag: "https://flagcdn.com/w320/se.png",
    code: "sv",
    language: "Swedish",
  },
  {
    name: "Kyrgyzstan",
    flag: "https://flagcdn.com/w320/kg.png",
    code: "ky",
    language: "Kyrgyz",
  },
  {
    name: "Russia",
    flag: "https://flagcdn.com/w320/ru.png",
    code: "ru",
    language: "Russian",
  },
  {
    name: "Malaysia",
    flag: "https://flagcdn.com/w320/my.png",
    code: "ms",
    language: "Malay",
  },
  {
    name: "Bosnia and Herzegovina",
    flag: "https://flagcdn.com/w320/ba.png",
    code: "bs",
    language: "Bosnian",
  },
  {
    name: "Ethiopia",
    flag: "https://flagcdn.com/w320/et.png",
    code: "am",
    language: "Amharic",
  },
  {
    name: "Slovenia",
    flag: "https://flagcdn.com/w320/si.png",
    code: "sl",
    language: "Slovenian",
  },
  {
    name: "Iceland",
    flag: "https://flagcdn.com/w320/is.png",
    code: "is",
    language: "Icelandic",
  },
  {
    name: "Luxembourg",
    flag: "https://flagcdn.com/w320/lu.png",
    code: "lb",
    language: "Luxembourgish",
  },
  {
    name: "Thailand",
    flag: "https://flagcdn.com/w320/th.png",
    code: "th",
    language: "Thai",
  },
  {
    name: "Belarus",
    flag: "https://flagcdn.com/w320/by.png",
    code: "be",
    language: "Belarusian",
  },
  {
    name: "Latvia",
    flag: "https://flagcdn.com/w320/lv.png",
    code: "lv",
    language: "Latvian",
  },
  {
    name: "Philippines",
    flag: "https://flagcdn.com/w320/ph.png",
    code: "tl",
    language: "Tagalog",
  },
  {
    name: "Denmark",
    flag: "https://flagcdn.com/w320/dk.png",
    code: "da",
    language: "Danish",
  },
  {
    name: "Somalia",
    flag: "https://flagcdn.com/w320/so.png",
    code: "so",
    language: "Somali",
  },
  {
    name: "Czechia",
    flag: "https://flagcdn.com/w320/cz.png",
    code: "cs",
    language: "Czech",
  },
  {
    name: "Rwanda",
    flag: "https://flagcdn.com/w320/rw.png",
    code: "rw",
    language: "Kinyarwanda",
  },
  {
    name: "Estonia",
    flag: "https://flagcdn.com/w320/ee.png",
    code: "et",
    language: "Estonian",
  },
  {
    name: "Romania",
    flag: "https://flagcdn.com/w320/ro.png",
    code: "ro",
    language: "Romanian",
  },
  {
    name: "Vietnamese",
    flag: "https://flagcdn.com/w320/vn.png",
    code: "vi",
    language: "Vietnamese",
  },
  {
    name: "Turkmenistan",
    flag: "https://flagcdn.com/w320/tm.png",
    code: "tk",
    language: "Turkmen",
  },
  {
    name: "Ireland",
    flag: "https://flagcdn.com/w320/ie.png",
    code: "ga",
    language: "Irish",
  },
  {
    name: "Tanzania",
    flag: "https://flagcdn.com/w320/tz.png",
    code: "sw",
    language: "Swahili",
  },
  {
    name: "Lithuania",
    flag: "https://flagcdn.com/w320/lt.png",
    code: "lt",
    language: "Lithuanian",
  },
  {
    name: "Slovakia",
    flag: "https://flagcdn.com/w320/sk.png",
    code: "sk",
    language: "Slovak",
  },
  {
    name: "Kazakhstan",
    flag: "https://flagcdn.com/w320/kz.png",
    code: "kk",
    language: "Kazakh",
  },
  {
    name: "Moldova",
    flag: "https://flagcdn.com/w320/md.png",
    code: "ro",
    language: "Romanian",
  },
  {
    name: "Armenia",
    flag: "https://flagcdn.com/w320/am.png",
    code: "hy",
    language: "Armenian",
  },
  {
    name: "Samoa",
    flag: "https://flagcdn.com/w320/ws.png",
    code: "sm",
    language: "Samoan",
  },
  {
    name: "Japan",
    flag: "https://flagcdn.com/w320/jp.png",
    code: "ja",
    language: "Japanese",
  },
  {
    name: "Madagascar",
    flag: "https://flagcdn.com/w320/mg.png",
    code: "mg",
    language: "Malagasy",
  },
  {
    name: "Iran",
    flag: "https://flagcdn.com/w320/ir.png",
    code: "fa",
    language: "Persian",
  },
  {
    name: "Albania",
    flag: "https://flagcdn.com/w320/al.png",
    code: "sq",
    language: "Albanian",
  },
  {
    name: "Myanmar",
    flag: "https://flagcdn.com/w320/mm.png",
    code: "my",
    language: "Burmese",
  },
  {
    name: "Bhutan",
    flag: "https://flagcdn.com/w320/bt.png",
    code: "dz",
    language: "Dzongkha",
  },
  {
    name: "Poland",
    flag: "https://flagcdn.com/w320/pl.png",
    code: "pl",
    language: "Polish",
  },
  {
    name: "Brunei",
    flag: "https://flagcdn.com/w320/bn.png",
    code: "ms",
    language: "Malay",
  },
  {
    name: "Malta",
    flag: "https://flagcdn.com/w320/mt.png",
    code: "mt",
    language: "Maltese",
  },
  {
    name: "Maldives",
    flag: "https://flagcdn.com/w320/mv.png",
    code: "dv",
    language: "Dhivehi",
  },
  {
    name: "Tonga",
    flag: "https://flagcdn.com/w320/to.png",
    code: "to",
    language: "Tongan",
  },
  {
    name: "Mongolia",
    flag: "https://flagcdn.com/w320/mn.png",
    code: "mn",
    language: "Mongolian",
  },
  {
    name: "Israel",
    flag: "https://flagcdn.com/w320/il.png",
    code: "he",
    language: "Hebrew",
  },
  {
    name: "Eritrea",
    flag: "https://flagcdn.com/w320/er.png",
    code: "ti",
    language: "Tigrinya",
  },
  {
    name: "Tajikistan",
    flag: "https://flagcdn.com/w320/tj.png",
    code: "tg",
    language: "Tajik",
  },
];
